ecosystem:
  main_project: drools
  projects:
  - name: drools
    regexs:
    - drools.*
    - incubator-kie-drools.*
  # - name: kie-jpmml-integration
  #   regexs:
  #   - kie-jpmml-integration.*
  - name: kie-benchmarks
    ignore_release: true
    regexs:
    - kie-benchmarks.*
    - incubator-kie-benchmarks.*
git:
  branches:
  - name: push-privilege
    main_branch: true
seed:
  config_file:
    git:
      repository: drools
      author:
        name: jstastny-cz
        credentials_id: ASF_Cloudbees_Jenkins_ci-builds
      branch: push-privilege
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: DROOLS_CI_NOTIFICATION_EMAILS
